In [5]:
import torch

a_tensor_initialization

In [6]:
t1 = torch.Tensor([1, 2, 3], device='cpu')
print(t1.dtype)
print(t1.device)
print(t1.requires_grad)
print(t1.size())
print(t1.shape)

t1_cpu = t1.cpu()

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


In [8]:
t2 = torch.tensor([1, 2, 3], device='cpu')
print(t2.dtype)
print(t2.device)
print(t2.requires_grad)
print(t2.size())
print(t2.shape)

t2_cpu = t2.cpu()

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


In [11]:
a1 = torch.tensor(1)
print(a1.shape, a1.ndim)

a2 = torch.tensor([1])
print(a2.shape, a2.ndim)

a3 = torch.tensor([1, 2, 3, 4, 5])
print(a3.shape, a3.ndim)

a4 = torch.tensor([[1], [2], [3], [4], [5]])
print(a4.shape, a4.ndim)

a5 = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)

a6 = torch.tensor([
    [[1], [2]],
    [[3], [4]],
    [[5], [5]]
])
print(a6.shape, a6.ndim)

a7 = torch.tensor([
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)


a8 = torch.tensor([
    [[[1, 2, 3],[2, 3, 4]]],
    [[[3, 1, 1],[4, 4, 5]]],
    [[[5, 6, 2],[6, 3, 1]]]
])
print(a8.shape, a8.ndim)

a9 = torch.tensor([
    [[[[1],[2],[3]],[[2],[3],[4]]]],
    [[[[3],[1],[1]],[[4],[4],[5]]]],
    [[[[5],[6],[2]],[[6],[3],[1]]]]
])

a10 = torch.tensor([
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5]
])
print(a10.shape, a10.ndim)

a10 = torch.tensor([
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]]
])
print(a10.shape, a10.ndim)


a11 = torch.tensor([
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])
print(a11.shape, a11.ndim)

torch.Size([]) 0
torch.Size([1]) 1
torch.Size([5]) 1
torch.Size([5, 1]) 2
torch.Size([3, 2]) 2
torch.Size([3, 2, 1]) 3
torch.Size([3, 1, 2, 1]) 4
torch.Size([3, 1, 2, 3]) 4
torch.Size([4, 5]) 2
torch.Size([4, 1, 5]) 3


ValueError: expected sequence of length 3 at dim 3 (got 2)

b_tensor_initialization_copy

In [12]:
import torch
import numpy as np

In [13]:
l1 = [1, 2, 3]
t1 = torch.Tensor(l1) #torch.Tensor : torch.float32

l2 = [1, 2, 3]
t2 = torch.tensor(l2) #torch.tensor : torch.int64

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)
# torch.as_tensor
# numpy 배열에서는 가능한 원본 메모리 공유
# 파이썬 리스트는 객체 포인터 참조이기 때문에 원본 메모리 공유 불가(복사본 생성)

l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1)
print(t2)
print(t3)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [14]:
l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4)
print(t5)
print(t6)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([100,   2,   3])


c_tensor_initialization_constant_values

In [15]:
t1 = torch.ones(size=(5,)) # or torch.ones(5) torch.ones 같은 함수는 튜플을 사용하지 않아도 내부에서 튜플로 변환 size=(5,) → 튜플형태
t1_like = torch.ones_like(input=t1) #input과 크기가 같은 텐서를 만들고 1로 채움
print(t1)
print(t1_like)

t2 = torch.zeros(size=(6,))
t2_like = torch.zeros_like(input=t2)
print(t2)
print(t2_like)

#input과 크기가 같은 텐서를 만들지만, 메모리만 할당하고 초기화는 하지 않음
#안에 들어가는 값이 쓰레기 값(garbage value)일 수 있기 때문에 재초기화 필수!!
t3 = torch.empty(size=(4,))
t3_like = torch.empty_like(input=t3)
print(t3)
print(t3_like)

t4 = torch.eye(n=3) # torch.eye : 단위 행렬(대각선은 1, 나머지는 0)
print(t4)

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([9.2194e-41, 0.0000e+00, 0.0000e+00, 0.0000e+00])
tensor([2., 0., 0., 0.])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


d_tensor_initialization_random_values

In [16]:
#torch.randint
# 주어진 [low,high) 범위 내에서 정수(int)난수 균일 분포 생성
t1 = torch.randint(low=10, high=20, size=(1, 2))
print(t1)

#torch.rand
#[0, 1)사이 난수 균일 분포 생성
t2 = torch.rand(size=(1, 3))
print(t2)

#torch.randn
#정규분포 N(0,1)(평균 0, 포준편차 1)에서 난수 생성, 신경망 가중치 초기화할 때 사용
t3 = torch.randn(size=(1, 3))
print(t3)

#torch.normal
#임의의 평균(mean), 표준편차(std)를 갖는 정규분포에서 샘플링
t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))
print(t4)

#torch.linspace
#start~end까지 등분된 구간으로 나눈 실수 값을 생성
#steps 개수만큼 값을 만듬(end 포함)
#연속 구간을 균등 분할할때 유용
t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5)

#torch.arange(start, end, step)
#start~end까지 step간격으로 값 생성
t6 = torch.arange(5)
print(t6)


tensor([[16, 14]])
tensor([[0.3413, 0.5217, 0.2111]])
tensor([[ 1.0257,  2.2207, -1.8842]])
tensor([[11.8888,  9.2489],
        [ 9.3426,  9.4615],
        [10.2818, 11.0190]])
tensor([0.0000, 2.5000, 5.0000])
tensor([0, 1, 2, 3, 4])


In [17]:
#torch.manual_seed()
#특정 시드(정수값)을 지정하여서 해당시드로는 난수 발생을 고정하여 동일한 결과를 공유할 수 있게 하는 함수
#실험 반복 시 결과 공유에 쓰임
#난수 생성의 시작점을 안정적으로 유지함
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

print()

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


e_tensor_type_conversion

In [18]:
a=torch.ones((2, 3))
print(a.dtype)

b=torch.ones((2, 3), dtype=torch.int16)
print(b)

c = torch.rand((2, 3), dtype=torch.float64) * 20
print(c)

d = b.to(torch.int32)
print(d)

#torch.double 사용 시 float64로 자료형태를 띔
#torch.short 사용 시 int16로 자료형태를 띔
double_d = torch.ones(10, 2, dtype=torch.double)
short_e = torch.tensor([1, 2], dtype=torch.short)

print(double_d)
print(short_e)

double_d = torch.zeros(10, 2).double()
short_e = torch.ones(10, 2).short()
print(double_d)
print(short_e)

double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.zeros(10, 2).to(dtype=torch.short)
print(double_d)
print(short_e)

double_d = torch.zeros(10, 2).type(torch.double)
short_e = torch.zeros(10, 2).type(dtype=torch.short)

print(double_d.dtype)
print(short_e.dtype)

# 서로 다른 유형일때는 int보다 float가 우선 시
double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype)

torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.0429,  7.2532, 19.6519],
        [10.8626,  2.1505, 19.6913]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)
tensor([1, 2], dtype=torch.int16)
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)
tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0.,

f_tensor_operations

In [19]:
#torch.add
#텐서 값 더하기
t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2)
t4 = t1 + t2
print(t3)
print(t4)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [20]:
#torch.sub
#텐서 값 뺄셈
t5 = torch.sub(t1, t2)
t6 = t1 - t2
print(t5)
print(t6)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [21]:
#torch.mul
#텐서 값 곱하기
t7 = torch.mul(t1, t2)
t8 = t1 *t2
print(t7)
print(t8)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [22]:
#torch.div
#텐서 값 나누기
t9 = torch.div(t1, t2)
t10 = t1 / t2
print(t9)
print(t10)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


g_tensor_operations_mm

In [23]:
#torch.dot()
#"스칼라 곱"을 수행
t1 = torch.dot(
    torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size()) # 2*2 + 3*1 = 7

#torch.mm()
#2차원의 계산 "행렬 곱"을 수행
t2 = torch.randn(2, 3) #torch.randn(n, p)
t3 = torch.randn(3, 2) #torch.randn(p, m)
t4 = torch.mm(t2, t3) #torch.randn(n, m)
print(t4, t4.size())

#torch.bmm
# 3차원 텐서의 "배치 수행 곱"
# 배치 크기는 동일해야함!!
t5 = torch.randn(10, 3, 4) #torch.randn(batch_size, n, p)
t6 = torch.randn(10, 4, 5) #torch.randn(batch_size, p, m)
t7 = torch.bmm(t5, t6) #torch.randn(batch_size, n, m)
print(t7.size())

tensor(7) torch.Size([])
tensor([[1.6750, 2.2840],
        [0.0956, 1.0294]]) torch.Size([2, 2])
torch.Size([10, 3, 5])


h_tensor_operations_matmul

In [24]:
# vector x vector : dot product
# 두 텐서가 모두 1차원인 경우 "내적"으로 계산
t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1, t2).size())

# 행렬 x 벡터 : 브로드캐스팅-내적
t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(torch.matmul(t3, t4).size())

# 배치 행렬 x 벡터 : 브로드캐스팅-내적
# 1차원 텐서(벡터)를 열 벡터로 취급 [4, 1] 이후 [3, 4] x [4, 1] -> [3, 1] -> [3]
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
print(torch.matmul(t5, t6).size())

# 배치 행렬 x 배치 행렬 : bmm
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size())

# 배치 행렬 x 행렬 : bmm
# 한쪽 텐서만 배치 차원이 있다면 다른 텐서는 모든 배치에 대해 브로드캐스팅됨.
# >> 배치 차원을 가진 텐서의 모든 배치에 대해 동일하게 복사되어 연산에 참여하는 것
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size())

torch.Size([])
torch.Size([3])
torch.Size([10, 3])
torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


i_tensor_broadcasting

In [25]:
# 1차원 텐서 x 파이썬 실수 : 브로드캐스팅 (파이썬 실수 → 0차원 텐서-스칼라)
t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2)

tensor([2., 4., 6.])


In [26]:
# 브로드캐스팅-가상확장
# t4의 모양이 t3와 호환되도록 (1, 2)모양으로 간주
t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4)

tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])


In [27]:
t5 = torch.tensor([[1., 2.],[3., 4.]])
print(t5 + 2.0) #t5.add(2.0)
print(t5 - 2.0) #t5.sub(2.0)
print(t5 * 2.0) #t5.mul(2.0)
print(t5 / 2.0) #t5.div(2.0)

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [28]:
# 텐서에 함수 적용
def normalize(x):
    return x / 255

t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())

torch.Size([3, 28, 28])


In [29]:
t7 = torch.tensor([[1, 2],[0, 3]])
t8 = torch.tensor([[3, 1]])
t9 = torch.tensor([[5], [2]])
t10 = torch.tensor([7])
print(t7 + t8)
print(t7 + t9)
print(t8 + t9)
print(t7 + t10)

tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])


In [30]:
# 브로드캐스팅 규칙
# 두 텐서의 모양을 뒤에서부터 비교
# 최종 결과 모양
# 연산이 간으한 경우, 결과 텐서의 모양은 각 차원에서 입력 텐서의 가장 큰 크기를 따름

# 첫 번째 차원이 t11은 4이지만, torch.rand(3, 2)는 없음
# 이 경우 torch.rand(3, 2)의 모양을 (1, 3, 2)로 가상 확장
t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)
print(t12.shape)

t13 = torch.ones(4, 3, 2)
t14 = t12 * torch.rand(3, 1)
print(t14.shape)

t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)
print(t16.shape)

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)
print((t17 + t18).size)

torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
<built-in method size of Tensor object at 0x0000020A1FA3D950>


In [31]:
t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size)

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size)

#브로드캐스팅 규칙 위배
# 1. 두 텐서의 크기가 같아야함
# 2. 둘 중 하나는 차원의 크기가 1이어야함
# 밑에 수식은 규칙 2 위배
# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size())

<built-in method size of Tensor object at 0x0000020A1FA3F160>
<built-in method size of Tensor object at 0x0000020A1FA3E850>


In [32]:
t27 = torch.ones(4) * 5
print(t27)

# torch.pow(input, exponent)
# input 텐서의 각 요소를 exponent만큼 거듭제곱
t28 = torch.pow(t27, 2)
print(t28)

exp = torch.arange(1., 5.)
a = torch.arange(1., 5.)
t29 = torch.pow(a, exp)
print(t29)

tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1.,   4.,  27., 256.])


j_tensor_indexing_slicing

In [33]:
x = torch.tensor(
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9],
     [10, 11, 12, 13, 14]]
)

print(x[1])
print(x[:, 1])
print(x[1, 2])
print(x[:, -1])

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])


In [34]:
y = torch.zeros((6, 6))
y[1:4, 2] = 1
print(y)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])


In [35]:
z = torch.tensor(
    [[1, 2, 3, 4],
     [2, 3, 4, 5],
     [5, 6, 7, 8]]
)
print(z[:2])
print(z[1:, 1:3])
print(z[:, 1:])

z[1:, 1:3] = 0
print(z)

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


k_tensor_reshaping

In [36]:
# .view(a, b) : [a, b]형태로 reshapeing
# .reshape(a, b) : [a, b]형태로 reshapeing

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)
t3 = t1.reshape(1, 6)
print(t2)
print(t3)

t4 = torch.arange(8).view(2, 4)
t5 = torch.arange(6).view(2, 3)
print(t4)
print(t5)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [37]:
#squeeze() : 크기가 1인 모든 차원을 제거
#squeeze(n) : n번째 차원이 1인 경우 제거
t6 = torch.tensor([[[1], [2], [3]]]) #torch.size(1, 1, 3, 1)
t7 = t6.squeeze()
t8 = t6.squeeze(0)
print(t7)
print(t8)

tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])


In [38]:
t9 = torch.tensor([1, 2, 3])

#unsqueeze(n) :input 텐서의 특정위치에 텐서에 크기가 1인 새로운 차원을 추가
t10 = t9.unsqueeze(1)
print(t10)

t11 = torch.tensor(     #tensor.size(2, 3)
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1)  #tensor.size(2, 1, 3)
print(t12, t12.shape)

tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])


In [39]:
# flatten(): 다차원의 텐서를 1차원 텐서로 펼치는 함수
# torch.flatten(input, start_dim=0, end_dim=-1)는 지정된 start_dim부터 end_dim까지의 차원을 1차원으로 병합합니다
t13 = torch.tensor([[1, 2, 3],[4, 5, 6]])
t14 = t13.flatten()
print(t14)

t15 = torch.tensor([[[1, 2],    #tensor.size(2, 2, 2)
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)

t17 = torch.flatten(t15, start_dim=1) #tensor.size(2, 1, 1)
print(t16)
print(t17)

tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [40]:
# torch.permute(input, dims=(a, b)) : dims=(a, b) 순서로 차원 재배열
t18 = torch.randn(2, 3, 5)
print(t18.shape)  # torch.Size([2, 3, 5])
print(torch.permute(t18, (2, 0, 1)).size())

t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

t20 = torch.permute(t19, dims=(0, 1))
t21 = torch.permute(t19, dims=(1, 0))
print(t20)
print(t21)

# torch.transpose(input, dim0, dim1) : input의 두 차원(dim0, dim1)을 바꿈 (전치행렬)
# torch.t()와 동일
t22 = torch.transpose(t19, 0, 1)
print(t22)

t23 = torch.t(t19)
print(t23)

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


l_tensor_concat

In [41]:
# torch.cat(tensors, dim=0) : 텐서들의 지정된 차원을 따라 "연결하는" 함수
# 주의! 나머지 차원들은 동일해야함!!
t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

t4 = torch.cat([t1, t2, t3], dim=1)
print(t4.shape)

torch.Size([2, 6, 3])


In [42]:
t5 = torch.arange(0, 3)  # tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # tensor([3, 4, 5, 6, 7])

t7 = torch.cat((t5, t6), dim=0) # 차원 0에 따라 연결 >>> torch.Size([8])
print(t7.shape)
print(t7)

torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])


In [43]:
t8 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t9 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])

# 2차원 텐서간 병합
t10 = torch.cat((t8, t9), dim=0) # torch.Size([4, 3])
print(t10.size())
print(t10)

t11 = torch.cat((t8, t9), dim=1) #torch.Size([2, 6])
print(t11.size())
print(t11)

torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])


In [44]:
t12 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t13 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])
t14 = torch.arange(12, 18).reshape(2, 3)  # torch.Size([2, 3])

t15 = torch.cat((t12, t13, t14), dim=0) # torch.Size([6, 3])
print(t15.size())
print(t15)

t16 = torch.cat((t12, t13, t14), dim=1) # torch.Size([2, 9])
print(t16.size())
print(t16)

torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])


In [45]:
t17 = torch.arange(0, 6).reshape(1, 2, 3)  # torch.Size([1, 2, 3])
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # torch.Size([1, 2, 3])

t19 = torch.cat((t17, t18), dim=0) # torch.Size([2, 2, 3])
print(t19.size())
print(t19)

t20 = torch.cat((t17, t18), dim=1) # torch.Size([1, 4, 3])
print(t20.size())
print(t20)

t21 = torch.cat((t17, t18), dim=2) # torch.Size([1, 2, 6])
print(t21.size())
print(t21)

torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])


m_tensor_stacking

In [46]:
# torch.stack() : 여러 텐서를 쌓아서 새로운 차원을 추가하는 방식으로 결합
# 새로운 차원의 숫자는 텐서의 갯수
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

t3 = torch.stack([t1, t2], dim=0) # 차원 0번째에 크기가 2인 차원 추가, 깊이 방향으로 쌓는 모양
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
print(t3)
print(t3.shape, t3.equal(t4))

t5 = torch.stack([t1, t2], dim=1) # dim=1 >> 각 행을 옆으로 쌓는 모양
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5)
print(t5.shape, t5.equal(t6))

t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7)
print(t7.shape, t7.equal(t8))

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
torch.Size([2, 2, 3]) True
tensor([[[ 1,  2,  3],
         [ 7,  8,  9]],

        [[ 4,  5,  6],
         [10, 11, 12]]])
torch.Size([2, 2, 3]) True
tensor([[[ 1,  7],
         [ 2,  8],
         [ 3,  9]],

        [[ 4, 10],
         [ 5, 11],
         [ 6, 12]]])
torch.Size([2, 3, 2]) True


In [47]:
t9 = torch.arange(0, 3)  # tensor([0, 1, 2])
t10 = torch.arange(3, 6)  # tensor([3, 4, 5])

print(t9.size(), t10.size()) # torch.Size([3]) torch.Size([3])

t11 = torch.stack((t9, t10), dim=0) # torch.Size([2,3])
print(t11.size())
print(t11)

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))

t13 = torch.stack((t9, t10), dim=1) # # >>> torch.Size([3,2])
print(t13.size())
print(t13)

t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))

torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


n_tensor_vstack_hstack

In [48]:
# torch.vstack : 텐서들을 "수직(vertical)"으로, 즉 행(row)을 따라 결합
# torch.cat(..., dim=0)과 동일한 기능
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2))
print(t3)
print(t3.shape)

t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5))
print(t6)
print(t6.shape)

t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)

t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)

t9 = torch.vstack([t7, t8])
print(t9)
print(t9.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
torch.Size([6, 1])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])
torch.Size([4, 2, 3])


In [49]:
# torch.hstack : 텐서들을 "수평(horizontal)"으로, 즉 열(column)을 따라 결합
# torch.cat(..., dim=1)과 동일한 기능
t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))
print(t12)
print(t12.shape)

t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))
print(t15)
print(t15.shape)

t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)

t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)

t18 = torch.hstack([t16, t17])
print(t18)
print(t18.shape)

tensor([1, 2, 3, 4, 5, 6])
torch.Size([6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([3, 2])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])
torch.Size([2, 4, 3])


숙제 후기

처음에는 파이썬과 비슷한 부분이 많아서 굳이 해야하나 생각했지만
차원에 관하여 코드를 작성하며 공부하면서 제 생각과 다른 구조가 나오는 경우가 많아지면서 뒷 부분에는 많은 시간을 할애한 것 같습니다.
예전 기초데이터과학이라는 과목을 수강할 때 데이터 전처리에 대해 공부하였는데 이걸 먼저 알고 수강하였다면 큰 도움이 될 것 같다는 생각을 하게 되었습니다.
데이터 전처리를 할 때 이번 과제를 하면서 공부한 것이 큰 도움이 될 것 같습니다.